version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cQ8-L4Q22LMz6BgWVoIw
      POSTGRES_DB: simulation-events
    volumes:
      - db-data:/var/lib/postgresql/data
  frontend:
    build: web
    ports:
      - "9500:9500"
  kafka_ui:
    image: provectuslabs/kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    env_file:
      - .env
    ports:
      - 8081:8080

volumes:
  db-data: