version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    # environment:
    #   - VIEWS_DIR=/app/internal/views
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cQ8-L4Q22LMz6BgWVoIw
      POSTGRES_DB: simulation-events
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: